#!/usr/bin/env bash	
set -e # Exit on any child process error

source ./scripts/setup_env

npm run clean

mkdir -p dist

echo "Transpile ES6 to CJS"
npm install
npm run transpile -- --ignore spec.js

echo "Processing infrastructure template for $DRONE_BRANCH"
echo "{\"AWS_ACCESS_KEY_ID\":\"${AWS_ACCESS_KEY_ID}\",
\"AWS_SECRET_ACCESS_KEY\":\"${AWS_SECRET_ACCESS_KEY}\",
\"AWS_DEFAULT_REGION\":\"${AWS_DEFAULT_REGION}\",
\"AWS_ACCOUNT_ID\":\"${AWS_ACCOUNT_ID}\"}" | mustache - ./infrastructure/constants/$DRONE_BRANCH.json > ./dist/constants.json
cat ./dist/constants.json | mustache - ./infrastructure/cloudformation.yaml > ./dist/cloudformation.yaml

echo "Production NPM Install"
rm -rf ./node_modules
npm install --production
pushd ./dist/cjs
ln -s ../../node_modules/
popd

echo "Packaging Code"
pushd dist/cjs
zip -q -r ../mission-life-sponsorship-upload-limit-handler.zip .
